### PR TITLE
Use special signal termination on Windows

### PR DESCRIPTION
**Pull request by npeihl**
Windows doesn't support SIGHUP so we check the os type and use SIGTERM
when using Windows.

### CODE REVIEW

**Comment by mourner** [comment]
@npeihl do you know why we use `SIGHUP` in the first place? Would just calling `kill` without arguments (defaulting to `SIGTERM`) be good enough?

**Comment by npeihl** [comment]
@mourner I think we're using `SIGHUP` to give the worker a chance to send a message back to `index.js` via `ee`. If we use `SIGTERM` it might terminate the worker without triggering the `process.send(message)` function [here](https://github.com/mapbox/tile-reduce/blob/master/worker.js#L4).

I haven't tested this, but that's my hypothesis.

**Comment by npeihl** [comment]
@mourner Just noticed your PR. Wow! Great work! I'll concede my PR if using `kill()` rather than `kill(SIGHUP)` on POSIX systems is preferred. cc @morganherlocker

**Comment by mourner** [comment]
> If we use SIGTERM it might terminate the worker without triggering the process.send(message) function here.

I think that's fine since by the time the shutdown is called, the main thread has received all the data. But even if we want to go around that, SIGTERM [can be intercepted](http://joseoncode.com/2014/07/21/graceful-shutdown-in-node-dot-js/) in the worker (it's not a force-kill).

**Pull request closed without merging**
