### PR TITLE
tile-reduce shouldn't be used on node v4+

### PR DESCRIPTION
**Pull request by tyrasd**
Since [node v4.0.0](https://github.com/nodejs/node/blob/master/CHANGELOG.md#2015-09-08-version-400-stable-rvagg), `child_node.send` is an async operation. tile-reduce apparently assumes that tile jobs don't have any non-negligible async operation parts, because otherwise new tiles are being loaded into memory before the closure of an ongoing tile job is freed up (resulting in some serious memory leakage/over-usage).

While this behaviour is true for any async operations inside any `map.js` operation (which one can typically avoid), one cannot avoid the inherent use of `child_node.send` in `worker.js`, which is a long-lasting operation when transmitting largish amounts of data to the main thread.

Analogously, writing to `process.stdout` (when called from a *silent* child_node) appears to be a sync operation in node v0.12, while it isn't anymore in node v4 (haven't found any documentation about this change, but it's likely related to child_node.send in some way internally). That's then also causing the symptoms from above and possibly also #77/#78.

Of course, the real solution to this problem would be to convert the worker's job-queue into something that can actually handle async *map* scripts, which shouldn't be too hard. I'll see if I can find the time to try that.

### CODE REVIEW

**Comment by tyrasd** [comment]
> Of course, the real solution to this problem would be to convert the worker's job-queue into something that can actually handle async map scripts, which shouldn't be too hard.

See #83

**Comment by mourner** [comment]
> tile-reduce apparently assumes that tile jobs don't have any non-negligible async operation parts, because otherwise new tiles are being loaded into memory before the closure of an ongoing tile job is freed up (resulting in some serious memory leakage/over-usage).

Did you actually experience this in a particular use case? We have a manual rate limiting code that prevents tile-reduce from processing too many tiles at once. 

It also doesn't matter for the current implementation whether send is sync or async — I don't see any side effects from this, unless I'm missing something.

**Comment by tyrasd** [comment]
> particular use case

I'm trying to use tile-reduce to filter out certain categories of objects from osm-qa-tiles (e.g. all buildings, roads, etc.). Which doesn't take much time in terms of actual processing, but a decent amount of time is spend shoving the data around from workers back to the main thread.

Here's a stripped down version that just echoes back all geojson content: https://gist.github.com/tyrasd/ed0d453b3627e0afae9d – use with `npm install https://github.com/mapbox/tile-reduce#11c523d8bd9cfaf0a50d64df79f152a6a54cc850`, call it like `node some-osm-qa-extract.mbtiles > /dev/null`, I was using `italy.mbtiles` for my tests.

This repeatedly crashes with a `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory` on my machine (Ubuntu 14.04, 8GB ram) when using node v4 (or v5). On node v0.12 it works just fine. See also the different call patterns attached to the gist: on node 4 the worker basically only loads vector tiles into memory, while on 0.12 the tiles are worked on one after each other (which I assume is the intended behaviour).

PR #83 tries to equalize the call patterns across different node versions, making program behavior more reproducible.

> We have a manual rate limiting code that prevents tile-reduce from processing too many tiles at once.

You mean [`options.batch`](https://github.com/mapbox/tile-reduce/blob/master/src/index.js#L28)? I haven't seen that before, but IMHO 5000 seems much to high as a default, if we're really talking about limiting the amount of vector tile data to be preloaded on the workers. Also, the option is not documented as far as I can see, is it?

**Comment by mourner** [comment]
-> #83

**Pull request closed without merging**
